package com.frota.checklist.security;

public enum Permissao {
    FROTA_CONSULTAR,
    FROTA_OPERAR,
    VEICULO_GERIR,
    VEICULO_LIBERAR,
    CADASTRO_EXCLUIR,
    MISSAO_REGISTRAR,
    MISSAO_COMPLEMENTAR,
    MISSAO_CORRIGIR,
    MISSAO_ENCERRAR_EXCECAO,
    VISTORIA_CONSULTAR,
    VISTORIA_CORRIGIR,
    MOTORISTA_GERIR,
    ALOCACAO_CONSULTAR,
    ALOCACAO_GERIR,
    RELATORIO_EXPORTAR,
    ESTATISTICA_CONSULTAR,
    CONFIGURACAO_GERIR,
    ACESSO_GERIR
}
