package com.frota.checklist.dto;

public enum TipoEventoHistoricoVeiculo {
    MISSAO_INICIADA,
    MISSAO_FINALIZADA,
    MISSAO_HORARIO_AJUSTADO,
    MISSAO_EDITADA_ADMIN,
    CHECKLIST_SAIDA,
    CHECKLIST_CHEGADA,
    EXCECAO_ABERTA,
    EXCECAO_REGULARIZADA,
    VIAGEM_INICIADA,
    VIAGEM_FINALIZADA,
    USO_EXTERNO_INICIADO,
    USO_EXTERNO_FINALIZADO,
    VISTORIA_COMPLETA_SAIDA,
    VISTORIA_COMPLETA_CHEGADA,
    STATUS_ALTERADO
}
