package com.frota.checklist.entity;

public enum AcaoAuditoriaMissao {
    ABERTURA_CHECKLIST,
    ABERTURA_SEM_CHECKLIST,
    ABERTURA_LEGADO_RECONSTRUIDA,
    ENCERRAMENTO_CHECKLIST,
    ENCERRAMENTO_SEM_CHECKLIST,
    ENCERRAMENTO_ADMINISTRATIVO,
    ATUALIZACAO_DADOS_ADMINISTRATIVOS
}
