package com.frota.checklist.entity;

public enum MotivoExcecaoMissao {
    TROCA_RAPIDA_VEICULO,
    CHUVA_FORTE,
    URGENCIA_OPERACIONAL,
    SEM_TEMPO_OPERACIONAL,
    FALHA_CAMERA,
    SEM_INTERNET,
    SEM_CELULAR,
    BATERIA_DESCARREGADA,
    APP_INDISPONIVEL,
    OUTROS
}
